# Generated by Django 4.0.2 on 2022-04-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_image', models.ImageField(blank=True, upload_to='images/messages/', verbose_name='Изображение')),
                ('message_time', models.DateTimeField(verbose_name='Время отправления')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sender_visibility', models.BooleanField(default=True, verbose_name='Отображение у отправителя')),
                ('reciever_visibility', models.BooleanField(default=True, verbose_name='Отображение у получателя')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
